/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p77.unidad4.vista;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import utp.misiontic2022.c2.p77.unidad4.controlador.Controlador;
import utp.misiontic2022.c2.p77.unidad4.modelo.vo.Book;
import utp.misiontic2022.c2.p77.unidad4.modelo.vo.BookStock;

/**
 *
 * @author 3mer
 */
public class BookShop_GUI extends javax.swing.JFrame {
    
    private Controlador controlador;
    private BooksTM booksTM;
    private BookStockTM bookStockTM;

    /**
     * Creates new form BookShop_GUI
     */
    public BookShop_GUI() {
        controlador = new Controlador();
        initComponents();
        valoresIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pBook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        spBook = new javax.swing.JSplitPane();
        pFormBook = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idBook = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnSaveBook = new javax.swing.JButton();
        pTableBook = new javax.swing.JPanel();
        pbtnBook = new javax.swing.JPanel();
        btnNuevoLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        pStock = new javax.swing.JPanel();
        spStock = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        amountStock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addStock = new javax.swing.JTextField();
        saveStock = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        idBookStock = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookStock = new javax.swing.JTable();
        pSale = new javax.swing.JPanel();
        mbOpciones = new javax.swing.JMenuBar();
        mFile = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        mOption = new javax.swing.JMenu();
        miBooks = new javax.swing.JMenuItem();
        miStock = new javax.swing.JMenuItem();
        miSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BookShop");

        pBook.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Libros");
        pBook.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        spBook.setDividerLocation(35);
        spBook.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spBook.setEnabled(false);

        jLabel2.setText("ID:");

        idBook.setEditable(false);
        idBook.setFocusable(false);

        jLabel3.setText("Title:");

        jLabel4.setText("ISBN:");

        jLabel5.setText("Year:");

        btnSaveBook.setText("Save");
        btnSaveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFormBookLayout = new javax.swing.GroupLayout(pFormBook);
        pFormBook.setLayout(pFormBookLayout);
        pFormBookLayout.setHorizontalGroup(
            pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFormBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveBook, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pFormBookLayout.setVerticalGroup(
            pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pFormBookLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(pFormBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveBook))
                .addContainerGap())
        );

        spBook.setTopComponent(pFormBook);

        pTableBook.setLayout(new java.awt.BorderLayout());

        pbtnBook.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNuevoLibro.setText("New");
        btnNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoLibroActionPerformed(evt);
            }
        });
        pbtnBook.add(btnNuevoLibro);

        btnEliminarLibro.setText("Delete");
        btnEliminarLibro.setEnabled(false);
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });
        pbtnBook.add(btnEliminarLibro);

        pTableBook.add(pbtnBook, java.awt.BorderLayout.PAGE_END);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        pTableBook.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        spBook.setRightComponent(pTableBook);

        pBook.add(spBook, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Books", pBook);

        pStock.setLayout(new java.awt.BorderLayout());

        spStock.setDividerLocation(35);
        spStock.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spStock.setEnabled(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(159, 100));

        jLabel6.setText("Amount:");

        amountStock.setEditable(false);
        amountStock.setFocusable(false);

        jLabel7.setText("addStock:");

        addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockActionPerformed(evt);
            }
        });

        saveStock.setText("Save");
        saveStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStockActionPerformed(evt);
            }
        });

        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBookStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveStock)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(amountStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(addStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveStock)
                    .addComponent(jLabel8)
                    .addComponent(idBookStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        spStock.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tblBookStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tblBookStock);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        spStock.setRightComponent(jPanel2);

        pStock.add(spStock, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Stock", pStock);

        javax.swing.GroupLayout pSaleLayout = new javax.swing.GroupLayout(pSale);
        pSale.setLayout(pSaleLayout);
        pSaleLayout.setHorizontalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pSaleLayout.setVerticalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Sales", pSale);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        mFile.setText("File");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mFile.add(miExit);

        mbOpciones.add(mFile);

        mOption.setText("Edit");

        miBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miBooks.setText("Books");
        miBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBooksActionPerformed(evt);
            }
        });
        mOption.add(miBooks);

        miStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miStock.setText("Stock");
        miStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStockActionPerformed(evt);
            }
        });
        mOption.add(miStock);

        miSales.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_LESS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSales.setText("Sales");
        miSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalesActionPerformed(evt);
            }
        });
        mOption.add(miSales);

        mbOpciones.add(mOption);

        setJMenuBar(mbOpciones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valoresIniciales() {
        try {
            var books = controlador.findAllBooks();
            
            booksTM = new BooksTM(books);
            tblBooks.setModel(booksTM);
            
            tblBooks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblBooks.getSelectionModel().addListSelectionListener((e) -> {
                var row = tblBooks.getSelectedRow();
                if (row == -1) {
                    limpiarCamposLibro();
                    btnEliminarLibro.setEnabled(false);
                } else {
                    var book = booksTM.getBook(row);
                    cargarCamposLibro(book);
                    btnEliminarLibro.setEnabled(true);
                }
            });
            
        } catch (SQLException e) {
        }
        
        try {
            var registrosbs = controlador.consultarStock();
            bookStockTM = new BookStockTM(registrosbs);
            tblBookStock.setModel(bookStockTM);
            
            tblBookStock.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            
            tblBookStock.getSelectionModel().addListSelectionListener((e) -> {
                var row = tblBookStock.getSelectedRow();
                if (row == -1) {
                    limpiarCamposStock();
                } else {
                    var bs = bookStockTM.getBook(row);
                    cargarCamposStock(bs);
                }
            });
            
        } catch (SQLException e) {
        }
        
    }
    
    private void cargarCamposStock(BookStock bs) {
        idBookStock.setText(String.valueOf(bs.getId()));
        amountStock.setText(String.valueOf(bs.getAmount()));
    }
    
    private void limpiarCamposStock() {
        idBookStock.setText("");
        amountStock.setText("");
        addStock.setText("");
    }
    
    private void cargarCamposLibro(Book book) {
        idBook.setText(String.valueOf(book.getId()));
        txtTitle.setText(book.getTitle());
        txtIsbn.setText(book.getIsbn());
        txtIsbn.setEnabled(false);
        txtYear.setText(String.valueOf(book.getYear()));
    }

    private void limpiarCamposLibro() {
        idBook.setText("");
        txtTitle.setText("");
        txtIsbn.setText("");
        txtIsbn.setEnabled(true);
        txtYear.setText("");
    }
    
    private void miBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBooksActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_miBooksActionPerformed

    private void miStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStockActionPerformed

        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_miStockActionPerformed

    private void miSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalesActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_miSalesActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicación?", 
                getTitle(), JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_miExitActionPerformed

    private void btnSaveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBookActionPerformed
        // Validar Campos (title, isbn, year) - Que no esten vacios
        if (txtTitle.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El titulo es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtTitle.requestFocus();
        }
        
        if (txtIsbn.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El ISBN es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtIsbn.requestFocus();
        }
        
        if (txtYear.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El año es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtIsbn.requestFocus();
        }
        
        try {
            String id = idBook.getText();
            String title = txtTitle.getText().trim();
            String isbn = txtIsbn.getText().trim();
            Integer year = Integer.valueOf(txtYear.getText().trim());
            
            if (id.isBlank()) {
                var book = controlador.createBook(title, isbn, year);
                booksTM.addBook(book);
            } else {
                var row = tblBooks.getSelectedRow();
                var book = controlador.updateBook(isbn, title, year);
                book.setId(Integer.valueOf(id));
                booksTM.setBook(row, book);
            }
            
            
            JOptionPane.showMessageDialog(this, "EL libro se guardo en la base de datos!");
            
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnSaveBookActionPerformed

    private void btnNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoLibroActionPerformed
        tblBooks.clearSelection();
        
        limpiarCamposLibro();
        
        txtTitle.requestFocus();
    }//GEN-LAST:event_btnNuevoLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Esta seguro de eliminar el libro?\nEl libro solo se va a eliminar si no hay ventas de este!",
            getTitle(),
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE)
        == JOptionPane.YES_OPTION) {

        try {
            var row = tblBooks.getSelectedRow();
            var delete = controlador.deleteBook(Integer.valueOf(idBook.getText()));
            if (delete) {
                booksTM.removeBook(row);
                JOptionPane.showMessageDialog(this, "Se ha eliminado el libro!");
            } else {
                JOptionPane.showMessageDialog(this, "Existen ventas de el libro, no se puede eliminar!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo ejecutar la acción!", getTitle(), JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStockActionPerformed

    private void saveStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStockActionPerformed
        // VAlidar que addStock no este vacio
        if (addStock.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "addStock no puede estar vacio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtTitle.requestFocus();
        }
        
        try {
            var row = tblBookStock.getSelectedRow();
            Integer id = Integer.valueOf(idBookStock.getText());
            Integer amount = Integer.valueOf(addStock.getText());
            
            Integer newAmount = Integer.valueOf(amountStock.getText()) - amount;
            controlador.updateStock(id, amount);
            
            JOptionPane.showMessageDialog(this, "Se actualizo el stock!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puedo ejecutar la acción!");
        }
    }//GEN-LAST:event_saveStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookShop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookShop_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addStock;
    private javax.swing.JTextField amountStock;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnNuevoLibro;
    private javax.swing.JButton btnSaveBook;
    private javax.swing.JTextField idBook;
    private javax.swing.JTextField idBookStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mFile;
    private javax.swing.JMenu mOption;
    private javax.swing.JMenuBar mbOpciones;
    private javax.swing.JMenuItem miBooks;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miSales;
    private javax.swing.JMenuItem miStock;
    private javax.swing.JPanel pBook;
    private javax.swing.JPanel pFormBook;
    private javax.swing.JPanel pSale;
    private javax.swing.JPanel pStock;
    private javax.swing.JPanel pTableBook;
    private javax.swing.JPanel pbtnBook;
    private javax.swing.JButton saveStock;
    private javax.swing.JSplitPane spBook;
    private javax.swing.JSplitPane spStock;
    private javax.swing.JTable tblBookStock;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTabbedPane tpPrincipal;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
