/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p77.unidad4.vista;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import utp.misiontic2022.c2.p77.unidad4.controlador.Controlador;
import utp.misiontic2022.c2.p77.unidad4.modelo.vo.Book;

/**
 *
 * @author 3mer
 */
public class Bookshop_GUI extends javax.swing.JFrame {
    
    private Controlador controlador;
    private BooksTM bookTM;

    /**
     * Creates new form Bookshop_GUI
     */
    public Bookshop_GUI() {
        controlador = new Controlador();
        initComponents();
        cargarLibros();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        pBooks = new javax.swing.JPanel();
        lBooks = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pCBook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnGuardarLibro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idBook = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnCrearLibro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        pStock = new javax.swing.JPanel();
        pSale = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmApp = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        jmVentanas = new javax.swing.JMenu();
        miBook = new javax.swing.JMenuItem();
        miSock = new javax.swing.JMenuItem();
        miSale = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BookShop");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pBooks.setLayout(new java.awt.BorderLayout());

        lBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lBooks.setText("Gestión de Libros");
        pBooks.add(lBooks, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(35);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setEnabled(false);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(160, 239));

        pCBook.setPreferredSize(new java.awt.Dimension(632, 15));

        jLabel1.setText("Libro:");

        jLabel2.setText("ISBN:");

        jLabel3.setText("Año:");

        btnGuardarLibro.setText("Guardar");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        javax.swing.GroupLayout pCBookLayout = new javax.swing.GroupLayout(pCBook);
        pCBook.setLayout(pCBookLayout);
        pCBookLayout.setHorizontalGroup(
            pCBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCBookLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        pCBookLayout.setVerticalGroup(
            pCBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarLibro)
                    .addComponent(jLabel4)
                    .addComponent(idBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(pCBook);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.FlowLayout(2));

        btnCrearLibro.setText("Nuevo");
        btnCrearLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearLibroActionPerformed(evt);
            }
        });
        jPanel3.add(btnCrearLibro);

        jButton2.setText("Eliminar");
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        pBooks.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        tpPrincipal.addTab("Books", pBooks);

        javax.swing.GroupLayout pStockLayout = new javax.swing.GroupLayout(pStock);
        pStock.setLayout(pStockLayout);
        pStockLayout.setHorizontalGroup(
            pStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        pStockLayout.setVerticalGroup(
            pStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Stock", pStock);

        javax.swing.GroupLayout pSaleLayout = new javax.swing.GroupLayout(pSale);
        pSale.setLayout(pSaleLayout);
        pSaleLayout.setHorizontalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        pSaleLayout.setVerticalGroup(
            pSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Sale", pSale);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        jmApp.setText("Archivo");

        miSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jmApp.add(miSalir);

        jMenuBar1.add(jmApp);

        jmVentanas.setText("Edit");

        miBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miBook.setText("Book");
        miBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBookActionPerformed(evt);
            }
        });
        jmVentanas.add(miBook);

        miSock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSock.setText("Stock");
        miSock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSockActionPerformed(evt);
            }
        });
        jmVentanas.add(miSock);

        miSale.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        miSale.setText("Sale");
        miSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaleActionPerformed(evt);
            }
        });
        jmVentanas.add(miSale);

        jMenuBar1.add(jmVentanas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        exit_app();
    }//GEN-LAST:event_miSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        exit_app();
    }//GEN-LAST:event_formWindowClosing

    private void miBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBookActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_miBookActionPerformed

    private void miSockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSockActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_miSockActionPerformed

    private void miSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaleActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_miSaleActionPerformed

    private void exit_app() throws HeadlessException {
        if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicación?",
                getTitle(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }
    
    private void cargarLibros() {
        try {
            var books = controlador.findAllBooks();
            
            bookTM = new BooksTM(books);
            tblBooks.setModel(bookTM);
            
            tblBooks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tblBooks.getSelectionModel().addListSelectionListener((e) -> {
                var row = tblBooks.getSelectedRow();
                if (row == -1) {
                    idBook.setText("");
                    txtTitle.setText("");
                    txtIsbn.setText("");
                    txtYear.setText("");
                } else {
                    var book = bookTM.getBook(row);
                    cargarCamposLibro(book);
                }
            });
        } catch (SQLException e) {
        }
    }
    
    private void cargarCamposLibro(Book book) {
        idBook.setText(String.valueOf(book.getId()));
        txtTitle.setText(book.getTitle());
        txtIsbn.setText(book.getIsbn());
        txtYear.setText(String.valueOf(book.getYear()));
    }
    
    private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroActionPerformed
        // Limpiar selección de la tabla
        tblBooks.clearSelection();
        // Lipiar form
        idBook.setText("");
        txtTitle.setText("");
        txtIsbn.setText("");
        txtYear.setText("");
        // Obtener foco
        txtTitle.requestFocus();
    }//GEN-LAST:event_btnCrearLibroActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
        // Validar campos (title, isbn)
        if (txtTitle.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El titulo es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtTitle.requestFocus();
        }
        
        if (txtIsbn.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "El isbn es obligatorio!", getTitle(), JOptionPane.WARNING_MESSAGE);
            txtIsbn.requestFocus();
        }
        // Enviar datos al controlador
        try {
            String id = idBook.getText();
            String title = txtTitle.getText().trim();
            String isbn = txtIsbn.getText().trim();
            Integer year = Integer.valueOf(txtYear.getText().trim());
            
            if (id.isBlank()) {
                var book = controlador.createBook(title, isbn, year);
                bookTM.addBook(book);
            } else {
                var row = tblBooks.getSelectedRow();
                var book = controlador.updateBook(isbn, title, year);
                
                bookTM.setBook(row, book);
            }
            
            JOptionPane.showMessageDialog(this, "Se ha guardado el libro!");
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookshop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookshop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookshop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookshop_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookshop_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearLibro;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JTextField idBook;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JMenu jmApp;
    private javax.swing.JMenu jmVentanas;
    private javax.swing.JLabel lBooks;
    private javax.swing.JMenuItem miBook;
    private javax.swing.JMenuItem miSale;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miSock;
    private javax.swing.JPanel pBooks;
    private javax.swing.JPanel pCBook;
    private javax.swing.JPanel pSale;
    private javax.swing.JPanel pStock;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTabbedPane tpPrincipal;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
